# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(default='\u8349\u7a3f', max_length=128, verbose_name='\u72b6\u6001'),
        ),
    ]
