# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostBaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.SlugField(max_length=30, unique=True)),
                ('machine_room', models.CharField(max_length=5)),
                ('create_time', models.DateField()),
                ('owner', models.CharField(max_length=15)),
                ('os', models.CharField(max_length=10)),
                ('machine_type', models.CharField(max_length=10)),
                ('account', models.CharField(blank=True, max_length=15)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('remark', models.CharField(blank=True, max_length=100)),
                ('phy_machine_flag', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HostGroupInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.SlugField(max_length=30, unique=True)),
                ('remark', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HostIPInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncname', models.CharField(max_length=15)),
                ('ncip', models.GenericIPAddressField()),
                ('hostbaseinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xcmdb_main.HostBaseInfo')),
            ],
        ),
        migrations.CreateModel(
            name='HostMapGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupid', models.IntegerField()),
                ('hostbaseinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xcmdb_main.HostBaseInfo')),
            ],
        ),
    ]
