# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcmdb_main', '0004_machineroominfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_category', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostBusiSysCate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_sys_category', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostEnvCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostenv', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='hostbaseinfo',
            name='app_category',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostbaseinfo',
            name='app_port',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostbaseinfo',
            name='business_sys_category',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostbaseinfo',
            name='hostenv',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machineroominfo',
            name='machine_room',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
